name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew run
        with:
          path: WordRiver/server
      - name: Build Client
        run: npm install
        with:
          path: WordRiver/client
        run: ng serve
        with:
          path: WordRiver/client
      - name: Build Database
        run: .\mongoseed.bat
        with:
          path: WordRiver/database